### ISSUE TITLE
@conda-forge-admin, please add bot automerge

### ISSUE THREAD

**Issue by jGaboardi** [conda-forge/libpysal-feedstock#8]
@conda-forge-admin, please add bot automerge

**Comment by conda-forge-linter** [comment]
Hi! This is the friendly automated conda-forge-webservice.

I just wanted to let you know that I added bot automerge in conda-forge/libpysal-feedstock#9.

**Comment by ocefpaf** [comment]
@jGaboardi this is a good idea. It works best if we add this test

```yaml
test:
  commands:
    - pip check
  requires:
    - pip
```

to the recipe. That way we "kind of" ensure that our build will have the right requirements.
